steps:
  
  # Build the base Deepdrive image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/deepdrive:3.0', '.']
  
  # Build the bot image for the "Domain Randomization Sanity" Bot League problem
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/deepdrive:bot_domain_randomization',
    '--build-arg', 'BASE_IMAGE=gcr.io/$PROJECT_ID/deepdrive:3.0',
    './botleague/bots/domain_randomization'
  ]
  
  # Build the problem image for the "Domain Randomization Sanity" Bot League problem
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/deepdrive:problem_domain_randomization',
    '--build-arg', 'BASE_IMAGE=gcr.io/$PROJECT_ID/deepdrive:3.0',
    './botleague/problems/domain_randomization'
  ]

# Push our built images to GCR
images:
- 'gcr.io/$PROJECT_ID/deepdrive:3.0'
- 'gcr.io/$PROJECT_ID/deepdrive:bot_domain_randomization'
- 'gcr.io/$PROJECT_ID/deepdrive:problem_domain_randomization'

# Store build logs in the CI logs GCS bucket
logsBucket: "deepdrive-ci-logs"
