version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          ENABLE_SIM_BUILD: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: sudo chown -R circleci:circleci /usr/local/share

      - restore_cache:
          keys:
            - dd-dependencies-{{ checksum ".ci/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - dd-dependencies-

      - run: pip install -r .ci/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: dd-dependencies-{{ checksum ".ci/requirements.txt" }}

      - run: pip install --upgrade --force-reinstall --ignore-installed --no-cache-dir git+git://github.com/botleague/botleague-helpers#egg=botleague-helpers
      - run: pip install --upgrade --force-reinstall --ignore-installed --no-cache-dir git+git://github.com/deepdrive/problem-constants#egg=problem-constants
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run: |
          echo "$DOCKER_PASS" | sudo docker login --username $DOCKER_USER --password-stdin
      - run: cd .ci && make run
      - run: python -u .ci/cloud_ci.py

