version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          ENABLE_SIM_BUILD: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: sudo chown -R circleci:circleci /usr/local/share
      - run: pip install -r .circleci/requirements.txt
      - run: pip install --upgrade --force-reinstall --ignore-installed --no-cache-dir git+git://github.com/botleague/botleague-helpers#egg=botleague-helpers
      - run: pip install --upgrade --force-reinstall --ignore-installed --no-cache-dir git+git://github.com/deepdrive/problem-constants#egg=problem-constants
      - run: python -u .circleci/cloud_ci.py

